# markdownlint schema example: <https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml>

# Default state for all rules

default: true

# MD isn't just previewed - its also READ as just the markdown - make that a little easier

MD009:
  false
  # This just isn't worth the noise in my world.

MD012:
  # Consecutive blank lines
  maximum: 2

# Markdown files don't need to observe a line length limit
MD013: false # line-length
